package com.likelion.likit.member.entity;

import lombok.Getter;

@Getter
public enum Major {
    ELECTRONIC_ENGINEERING("ELECTRONIC_ENGINEERING"),
    SEMICONDUCTOR_SYSTEM("SEMICONDUCTOR_SYSTEM"),
    CONTROL_AND_ROBOTICS("CONTROL_AND_ROBOTICS"),
    ELECTRONICS_AND_TELECOMMUNICATIONS("ELECTRONICS_AND_TELECOMMUNICATIONS"),
    ELECTRONICS_AND_ELECTRONICS("ELECTRONICS_AND_ELECTRONICS"),
    ELECTRONICS_IT_CONVERGENCE("ELECTRONICS_IT_CONVERGENCE"),
    ARCHITECTURE("ARCHITECTURE"),
    INDUSTRIAL_ENGINEERING("INDUSTRIAL_ENGINEERING"),
    INDUSTRIAL_MANAGEMENT_ENGINEERING("INDUSTRIAL_MANAGEMENT_ENGINEERING"),
    DESIGN_ENGINEERING("DESIGN_ENGINEERING"),
    CHEMICAL_MATERIALS_ENGINEERING("CHEMICAL_MATERIALS_ENGINEERING"),
    POLYMER_SCIENCE_AND_ENGINEERING("POLYMER_SCIENCE_AND_ENGINEERING"),
    MATERIALS_DESIGN_ENGINEERING("MATERIALS_DESIGN_ENGINEERING"),
    CHEMICAL_ENGINEERING("CHEMICAL_ENGINEERING"),
    MATERIALS_SCIENCE_AND_ENGINEERING("MATERIALS_SCIENCE_AND_ENGINEERING"),
    MECHANICAL_ENGINEERING("MECHANICAL_ENGINEERING"),
    MECHANICAL_DESIGN_ENGINEERING("MECHANICAL_DESIGN_ENGINEERING"),
    MECHANICAL_SYSTEM_ENGINEERING("MECHANICAL_SYSTEM_ENGINEERING"),
    ENVIRONMENTAL_ENGINEERING("ENVIRONMENTAL_ENGINEERING"),
    IT_CONVERGENCE("IT_CONVERGENCE"),
    MATHEMATICS_AND_BIG_DATA_SCIENCE("MATHEMATICS_AND_BIG_DATA_SCIENCE"),
    CHEMISTRY_AND_BIO_SCIENCE("CHEMISTRY_AND_BIO_SCIENCE"),
    BUSINESS_ADMINISTRATION("BUSINESS_ADMINISTRATION"),
    CIVIL_ENGINEERING("CIVIL_ENGINEERING"),
    COMPUTER_ENGINEERING("COMPUTER_ENGINEERING"),
    COMPUTER_SOFTWARE_ENGINEERING("COMPUTER_SOFTWARE_ENGINEERING"),
    ARTIFICIAL_INTELLIGENCE_ENGINEERING("ARTIFICIAL_INTELLIGENCE_ENGINEERING"),
    OPTICAL_ENGINEERING("OPTICAL_ENGINEERING"),
    MEDICAL_IT_CONVERGENCE_ENGINEERING("MEDICAL_IT_CONVERGENCE_ENGINEERING");
    private String major;

    Major(String major) {
        this.major = major;
    }
}
